// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqrwevwfhwhppjzulvqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xcndldndmaHdocHBqenVsdnFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTk4MTAsImV4cCI6MjA3MzY5NTgxMH0.WI0K_RamCIINgV19PXxcFdcoWxUXwiycCrI608mp-Pw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});